(library
 (name assignment01)
 (modules question1 question2)
 (inline_tests)
 (preprocess (pps ppx_inline_test)))

(executable
 (name main)
 (modules main)
 (libraries assignment01))

(executable
 (name question2)
 (modules question2))
(library
 (name assignment01)
 (modules question1 question2 question3 main))
